### ISSUE TITLE
Data mapper tool bar color 

### ISSUE THREAD

**Issue by dongniwang** [syndesisio/syndesis-datamapper-ui#64]
Hello all, things are looking great! Thank you for all the hard work! 

I was wondering if it's possible to tweak the color of the tool bar (see screenshot below) on Data Mapper UI to make it look more like a tool bar? Right now, the white color treatment kind of truncates the entire page and makes it disconnect with the main data mapper area. 

@sjcox-rh: do you have any good suggestion here? 

cc: @kahboom @gashcrumb 

![ipaas_data mapper_toolbar_4 21](https://cloud.githubusercontent.com/assets/24943812/25286192/e50edf60-268a-11e7-9428-000503f3c057.png)

**Comment by gashcrumb** [comment]
Is that toolbar just for those two icons?  Maybe there'd be a better location for them so the toolbar doesn't even need to be there...

**Comment by jbakermd** [comment]
There may be a couple more icons in the future on the toolbar. @gashcrumb is there a precedent somewhere within iPAAS for placing such icons w/ callback handlers on the system wide breadcrumbs toolbar shown above the white toolbar in the screenshot? if not, are there other examples of page-specific action toolbars within iPAAS we could look to for guidance?

**Comment by aaamold** [comment]
@kcbabo is this something we need to get done today for the Red Hat demo?  If so, we'd need a quick recommendation on the color to change the toolbar.  If it isn't urgent for today, it looks like we need to have a discussion on the color / function / location of the toolbar in total.

**Comment by kcbabo** [comment]
From my POV, I think this change can wait until we've had a chance to discuss in full and recommend a color.  WDYT @dongniwang ?

**Comment by dongniwang** [comment]
Yes, we can revisit this after summit. But for now could we at the very least try to make the breadcrumbs and the toolbar area the same color so they're grouped together visually (see attached UI design)? We can make them either both white or both gray? 

![ipaas_data mapper_toolbar](https://cloud.githubusercontent.com/assets/24943812/25289816/2e433e70-2699-11e7-90ca-1085e2f1621c.png)

**Comment by gashcrumb** [comment]
@dongniwang white seems like it'd be the way to go, I'd want to probably go and make the breadcrumb area white across all the editor pages, what do you think?

**Comment by dongniwang** [comment]
White is fine with me. At least we don't have to deal with the gray color not rendering properly issue before summit... @gashcrumb

**Comment by jbakermd** [comment]
Closing this issue. We agreed to have a transparent toolbar background color a few weeks after the summit demo. That update was made, and the change is currently visible within the latest version of the syndesis ui.
