### ISSUE TITLE
Rename repo to 'syndesis-datamapper-ui'?

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-datamapper-ui#66]
@jimmidyson think we should rename this repo to `syndesis-datamapper-ui` to be consistent with the `syndesis-datamapper` repo name?

@jbakermd CC

**Comment by jimmidyson** [comment]
:+1:

**Comment by gashcrumb** [comment]
Done, will put in a PR to syndesis-ui for the repo name change
