### ISSUE TITLE
Update angular dependencies to 4.x 

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-datamapper-ui#67]
As part of this issue we'll also need to update the angular dependencies in this component, will send along a PR.

https://github.com/syndesisio/syndesis-ui/issues/543

**Comment by jbakermd** [comment]
Before I merge it, I noticed the change to ngx-bootstrap - is this just a rename? I ask because the change between ng-bootstrap and ng2-bootstrap caused a bit of pain and re-engineering to get things working again.

**Comment by jbakermd** [comment]
@gashcrumb

**Comment by gashcrumb** [comment]
yeah, that was a rename.  Also the reason for the extra work migrating from ng-bootstrap to ng2-bootstrap was due to them being different implementations of the same thing.

Hold off merging this for now though, I'm not sure it's entirely ready.

**Comment by jbakermd** [comment]
ok.

**Comment by gashcrumb** [comment]
@jbakermd PR is ready to merge when you get a chance

**Comment by jbakermd** [comment]
merged (commit #68, 9476d91ec03c0e4885f3005876c67216130ef98d)

**Comment by jbakermd** [comment]
hey @gashcrumb, have there been further updates to the dependencies? I will have to do some rework in various components for the ngx-bootstrap update, and I'd prefer to do those changes once.

**Comment by gashcrumb** [comment]
Hey!  Looks like just a couple changes in this commit -> https://github.com/syndesisio/syndesis-ui/commit/349b747ca33aed26f904086a0fd86c1908b44fe8
