### ISSUE TITLE
Some folders in datamapper screen not visible after search

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-datamapper-ui#69]
Originally raised as https://github.com/syndesisio/syndesis-ui/issues/588

**Comment by jbakermd** [comment]
This issue has been fixed in our next-gen data mapper, which is in this repo now: https://github.com/atlasmap/atlasmap-ui

Note that the next-gen data mapper is not yet integrated with the larger Syndesis project.
